name: Pytest

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    name: "${{ matrix.test }} on ${{ matrix.os }}, py${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: ["ubuntu-latest", "ubuntu-20.04"]
        python-version: ["3.8"]
        test: ["all", "partial"]
        exclude:
          - python-version: 3.9
            test: coveralls
    defaults:
      run:
        # This is needed otherwise we can't activate the conda installation
        shell: bash -l {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: "synda"
          mamba-version: "*"
      # PARTIAL (speed up testing)
      - name: run partial install
        if: matrix.test == 'partial'
        run: |
          conda activate synda
          bash .github/scripts/install_env.sh "--no_cdo --no_synda"

      # ALL
      - name: run full install
        if: matrix.test == 'all'
        run: |
          conda activate synda
          bash .github/scripts/install_env.sh
          bash .github/scripts/install_tex.sh
      - name: set Synda config
        if: matrix.test == 'all'
        env:
          OPEN_ID: ${{ secrets.OPEN_ID }}
          OPEN_ID_KEY: ${{ secrets.OPEN_ID_KEY }}
        run: bash .github/scripts/write_synda_cridentials.sh
      - name: Download data with Synda
        if: matrix.test == 'all'
        run: bash .github/scripts/download_example_data.sh

      - name: Run the tests
        run:
          |
          coverage run --source=optim_esm_tools -m pytest -vsx --durations 0
          # coverage run --append --source=optim_esm_tools -m pytest --nbmake -n=auto ./notebooks

      - name: Upload coverage
        if: matrix.test == 'all'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
      - name: goodbye
        run: echo goodbye
