name: Synda download

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    name: "(${{ matrix.os }}, ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
        exclude:
          - python-version: 3.9
    defaults:
      run:
        # This is needed otherwise we can't activate the conda installation
        shell: bash -l {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: "synda"
          mamba-version: "*"
      - name: run install
        env:
          ST_HOME: ~/synda
        run: |
          conda info
          conda activate synda
          bash .github/scripts/install_env.sh --synda_dir $ST_HOME --no_cdo --only_synda
      - name: set Synda config
        env:
          OPEN_ID: ${{ secrets.OPEN_ID }}
          OPEN_ID_KEY: ${{ secrets.OPEN_ID_KEY }}
        run: bash .github/scripts/write_synda_cridentials.sh
      - name: Download data with Synda
        run: bash .github/scripts/download_example_data.sh
      - name: goodbye
        run: echo goodbye
