name: Synda download

on:
  workflow_dispatch:
  release:
    types: [ created ]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    name: "(${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.test }})"
    runs-on: ${{ matrix.os }}
    env:
      ST_HOME: ~/synda
    strategy:
      fail-fast: False
      matrix:
        os: [ "ubuntu-latest", "ubuntu-20.04"]
        python-version: [ "3.8", ]
        test: [ 'coveralls', ]
        exclude:
          - python-version: 3.9
            test: coveralls
    defaults:
      run:
        # This is needed otherwise we can't activate the conda installation
        shell: bash -l {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            activate-environment: "synda"
            mamba-version: "*"
      - name: run install
        run:
          |
            conda info
            conda activate synda
            bash .github/scripts/install_env.sh --synda_dir $ST_HOME
      - name: set Synda config
        env:
          OPEN_ID: ${{ secrets.OPEN_ID }}
          OPEN_ID_KEY: ${{ secrets.OPEN_ID_KEY }}
        run: bash .github/scripts/write_synda_cridentials.sh
      - name: Download data with Synda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          synda search -v cmip5.output1.MPI-M.MPI-ESM-LR.decadal1995.mon.land.Lmon.r2i1p1.v20120529
          synda search -f cmip5.output1.MPI-M.MPI-ESM-LR.decadal1995.mon.land.Lmon.r2i1p1.v20120529 baresoilFrac
          synda install cmip5.output1.MPI-M.MPI-ESM-LR.decadal1995.mon.land.Lmon.r2i1p1.v20120529 baresoilFrac -y
          synda daemon start
          synda queue
          synda watch
          sleep 60
          synda queue
          find $ST_HOME/data -type f

          synda install CMIP6.ScenarioMIP.CCCR-IITM.IITM-ESM.ssp585.r1i1p1f1.3hr.tas.gn.v20200915 -y
          synda daemon start ; synda queue; synda watch
      - name: goodbye
        run: echo goodbye
